services:
  postgres:
    image: postgres:15-alpine
    container_name: vessel_postgres
    environment:
      POSTGRES_USER: vessel
      POSTGRES_PASSWORD: vesselpassword
      POSTGRES_DB: vessel_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
